<?php
return [
    'checklists' => env('SERVICE_CHECKLISTS', false),
    'widget_template' => env('WIDGET_TEMPLATE_WEBHOOK', null),
    'devices_bulk_delete' => env('bulk_objects_delete', false),
    'custom_fields' => env('ENABLE_CUSTOM_FIELDS', true),
    'custom_fields_task' => env('ENABLE_CUSTOM_FIELDS_TASK', false),
    'notification_popops' => env('SHOW_POPUPS', false),
    'google_styled' => env('google_styled', false),
    'negative_device_service' => env('NEGATIVE_DEVICE_SERVICE', false),
    'custom_device_add' => env('ENABLE_CUSTOM_DEVICE_ADD', false),
    'device_type' => env('ENABLE_DEVICE_TYPE', true),
    'html_geolocation' => env('HTML_GEOLOCATION', false),
    'alert_time_duration' => env('ALERT_TIME_DURATION', false),
    'engine_hours_current_report' => env('ENGINE_HOURS_CURRENT_REPORT', true),
    'general_information_6_report' => env('GENERAL_INFORMATION_6_REPORT', false),
    'device_app_single_usage' => env('DEVICE_APP_SINGLE_USAGE', false),
    'media_categories' => env('ENABLE_MEDIA_CATEGORIES', false),
    'device_tracker_app_login' => env('ENABLE_TRACKER_APP_LOGIN', false),
    'external_url' => env('ENABLE_EXTERNAL_URL', false),
    'login_token' => env('ENABLE_LOGIN_TOKEN', false),
    'report_fuel_tank_usage' => env('REPORT_FUEL_TANK_USAGE', true),
    'beacons' => env('ENABLE_BEACONS', true),
    'forwards' => env('ENABLE_FORWARDS', false),
    'forward_custom' => env('ENABLE_FORWARD_CUSTOM', false),
    'forward_pegasus' => env('ENABLE_FORWARD_PEGASUS', false),
    'forward_macropoint' => env('ENABLE_FORWARD_MACROPOINT', false),
    'device_authentication_field' => env('ENABLE_DEVICE_AUTHENTICATION_FIELD', false),
    'sensor_type_anonymizer' => env('ENABLE_SENSOR_TYPE_ANONYMIZER', false),
    'one_session_per_user' => env('ENABLE_ONE_SESSION_PER_USER', false),
    'object_delete_pass' => env('object_delete_pass', null),
    'inaccuracy' => env('ENABLE_INACCURACY', false),
    'plan_templates' => env('ENABLE_PLAN_TEMPLATES', false),
    'device_models' => env('ENABLE_DEVICE_MODELS', false),
    'time_text' => env('ENABLE_TIME_TEXT', false),
    'street_view_frame' => env('ENABLE_STREET_VIEW_FRAME', false),
    'distance_point' => env('ENABLE_DISTANCE_POINT', false)
];