<?php
return [
    "web.url"  => env('TRACKER_WEB_URL', env('APP_URL', 'http://localhost')),
    "web.enable" => "true",
    "web.license" => "true",
    "tpdxsmhywddgptku" => "true",
    "web.type" => "api",
    "web.port" => env('TRACKER_WEB_PORT', 8082),
    "web.path" => "/opt/traccar/web",
    "geocoder.enable" => "false",
    "geocoder.type" => "google",
    "logger.enable" => "true",
    "logger.level" => "info",
    "logger.rotate" => "true",
    "logger.file" => \Illuminate\Support\Str::finish(env('logs_path', '/opt/traccar/logs'), '/') . 'tracker-server.log',
    "time.override" => "serverTime",
    "media.path" => env('media_path', '/var/www/html/requestPhoto/'),
    "redis.enable" => "true",
    "redis.database" => env('REDIS_HOST', "127.0.0.1"),
    "redis.port"     => env('REDIS_PORT', "6379"),
    "redis.deviceModels" => env('ENABLE_DEVICE_MODELS', false) ? 'true' : 'false',
    "user.password"  => env('admin_user', 'admin'),
    "server.ignoreCustomCommand" => "false",
    "processing.remoteAddress.enable" => "true",
    "database.driver" => "com.mysql.jdbc.Driver",
    "database.url" => "jdbc:mysql://127.0.0.1:3306/gpswox_traccar",
    "database.registerUnknown" => "true",
    "database.registerUnknown.defaultGroupId" => "0",
    "database.ignoreUnknown" => "false"
];